repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [ --fix ]                    # 自动修复
      - id: ruff-format                    # 自动格式化